name: Deploy to Roblox

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 手動実行も可能

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Setup Rojo
        uses: Roblox/setup-rojo@v1
        with:
          version: '7.x'
      
      - name: Build Roblox Place
        run: |
          # Rojoでビルドを試みる
          if command -v rojo &> /dev/null; then
            echo "Building with Rojo..."
            rojo build -o game.rbxlx
          else
            echo "Rojo not found, using custom build script..."
            python build_rbxlx.py
          fi
      
      - name: Upload to Roblox
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          PLACE_ID: ${{ secrets.PLACE_ID }}
          UNIVERSE_ID: ${{ secrets.UNIVERSE_ID }}
        run: |
          # APIキーを環境変数から取得するようにスクリプトを修正
          cat > upload.py << 'EOF'
          import os
          import requests
          import json
          
          # 環境変数から設定を取得
          ROBLOX_API_KEY = os.environ["ROBLOX_API_KEY"]
          PLACE_ID = os.environ["PLACE_ID"]
          UNIVERSE_ID = os.environ["UNIVERSE_ID"]
          
          def upload_to_roblox(file_path):
              """Robloxにアップロード"""
              print(f"Uploading to Roblox Place ID: {PLACE_ID}")
              
              url = f"https://apis.roblox.com/universes/v1/{UNIVERSE_ID}/places/{PLACE_ID}/versions"
              headers = {
                  "x-api-key": ROBLOX_API_KEY,
                  "Content-Type": "application/octet-stream"
              }
              
              with open(file_path, "rb") as file:
                  file_data = file.read()
              
              response = requests.post(url, headers=headers, data=file_data)
              
              if response.status_code == 200:
                  print("Successfully uploaded to Roblox!")
                  print(response.json())
                  return True
              else:
                  print(f"Failed to upload: {response.status_code}")
                  print(response.text)
                  return False
          
          # メイン処理
          success = upload_to_roblox("game.rbxlx")
          if not success:
              exit(1)
          EOF
          
          python upload.py